Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "CustomerId"
          "AttributeType": "S"
        - "AttributeName": "ReferrerId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "CustomerId"
          "KeyType": "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Referral"
      GlobalSecondaryIndexes:
        - IndexName: "ReferrerIdIndex"
          KeySchema:
            - AttributeName: "ReferrerId"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL